### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by youngbo9i** [yjslzx/GATECDA#1]
Hi, can you provide a list of the names of CircRNA and Drug in the dataset, thank you in advance.

**Comment by yjslzx** [comment]
We added the corresponding names of drug and circRNA to the map folder under the mydata folder，, thank you for your question。

**Comment by youngbo9i** [comment]
Thank you very much

**Comment by not4yazwz** [comment]
Hi, can you provide the host gene sequence of the circRNA in question?Tks very much!

**Comment by yjslzx** [comment]
The host genesequence of circRNA come from NCBI Gene Database. you can find it by circRNA's symbol.

**Comment by ProZhang-Gr** [comment]
您好，circRic数据库中查找到的其实是drug-gene，但是gene对应着多个circRNA，请问您是怎么处理的这个问题呢？还是说您一直应用的gene-drug这个关系？

![Image](https://github.com/user-attachments/assets/8f597414-2d09-410c-a5a3-449b4dd1052f)

**Comment by ProZhang-Gr** [comment]
我的问题可能会有些鲁莽，敬请见谅！我将会十分感谢您的回复，因为我觉的circRIC数据库对于CircRNA的标识存在问题，目前我也没搞懂问题出在哪里

**Comment by yjslzx** [comment]
非常感谢您的提问。
我们的研究是基于circRic数据库提供的数据进行的。很遗憾，由于数据库提供的数据的限制，我们也未能将数据源中的数据进一步地细分到具体的circRNA。我们认为这也是circRNA-drug这个研究方向进一步扩展的方向。
如果您对数据源有疑问，我们有提供相应文章的链接，还请您对相关作者进行提问。
衷心希望您能获得更多更详细的相关数据，在这个方向取得更大的研究成果。

**Comment by ProZhang-Gr** [comment]
我没有想到您居然会在这么短时间内回复我，真是很感激！
无论如何，感谢您的慷慨回复！

**Comment by ProZhang-Gr** [comment]
经过一段时间的学习后，我处理了我之前所遇见的问题！
你的代码习惯很好！我是特地来夸赞你的！
